### ISSUE TITLE
Inconsistency with the standard for `operatorSend` and `operatorBurn`

### ISSUE THREAD

**Issue by daejunpark** [jacquesd/eip777#56]
There is a discrepancy between the standard and the reference implementation regarding the `operatorSend` and `operatorBurn` functions:

The current standard (https://github.com/ethereum/EIPs/blob/b41669ede219b9599a6a1c637e578b8a444ad6b1/EIPS/eip-777.md):

> The value of from MAY be 0x0, then the from (token holder) used for the send MUST be msg.sender (the operator).

The current reference implementation of both `operatorSend` and `operatorBurn`:

https://github.com/jacquesd/ERC777/blob/896d077eb4b1beb0fc2258f9d4dff4b60478a479/contracts/ERC777BaseToken.sol#L118-L121

https://github.com/jacquesd/ERC777/blob/896d077eb4b1beb0fc2258f9d4dff4b60478a479/contracts/ERC777BaseToken.sol#L127-L130

**Comment by 0xjac** [comment]
This has actually been removed from the spec. I checked and the implementation should now match the spec with respect to this topic.
