### ISSUE TITLE
`event Minted` not updated in the reference implementation

### ISSUE THREAD

**Issue by tomtomjhj** [jacquesd/eip777#58]
In https://github.com/jacquesd/EIPs/blob/master/EIPS/eip-777.md,
```solidity
event Minted(address indexed operator, address indexed to, uint256 amount, bytes data, bytes operatorData)
```
reference implementation:
https://github.com/jacquesd/ERC777/blob/896d077eb4b1beb0fc2258f9d4dff4b60478a479/contracts/ERC777Token.sol#L38

**Comment by 0xjac** [comment]
Thanks, I forgot to close this issue, but it was closed in 6d27520cfa42ad7496f3de0f26d943cf72329a72.
