### ISSUE TITLE
how i can compile this project?

### ISSUE THREAD

**Issue by fffeniksss** [jacquesd/eip777#63]
how i can compile this project?
please provide detailed instructions

**Comment by mikgross** [comment]
Use Truffle with Ganache or the Remix IDE...

**Comment by d10r** [comment]
This should do it:
```
npm install
npm install -g truffle
truffle compile
```

**Comment by 0xjac** [comment]
@mGrossSRT @d10r thanks for your answers they are both correct.

Note that `truffle` is a dev depedency so installing it globally (`npm install -g truffle` is not needed)

There are also convenience scripts to compile it:

`npm run build:sol`: to compile the contracts
`npm run build` to clean the past compiled contracts and compile from scratch
